language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository -y ppa:apokluda/boost1.53
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-system1.53-dev libstdc++-4.8-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DKunlaboro_BOOST=1 -DKunlaboro_BUILD_TESTS=1 ..

script: 
  - make Kunlaboro
  - make runtests