language: cpp
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
      env: COMPILER=g++-4.9
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#            - george-edison55-precise-backports
#          packages:
#            - clang-3.6
#            - cmake
#            - cmake-data
#      env: COMPILER=clang++-3.6

before_script:
  - mkdir build
  - cd build
  - CXX=$COMPILER cmake -DKunlaboro_BUILD_TESTS=1 ..

script: 
  - make -j2
  - tests/testsuite
