language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-all-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib; cd -"
before_script:
  - cmake -DKunlaboro_BOOST=1 .
script: "make && make test"