version: "{build}"

platform:
    - Win32
    - x64

configuration:
    - Debug

matrix:
    fast_finish: true

shallow_clone: true

clone_folder: C:\projects\Kunlaboro

before_build:
    - cmd: mkdir C:\projects\Kunlaboro\build
    - cmd: cd C:\projects\Kunlaboro\build
    - cmd: if %PLATFORM%==Win32 cmake .. -G"Visual Studio 12 2013" -Tv120_xp 
    - cmd: if %PLATFORM%==x64 cmake .. -G"Visual Studio 12 2013 Win64"

build:
    project: C:\projects\Kunlaboro\build\Kunlaboro.sln

test: off
